name: Feature Request
description: Suggest an idea for calista
title: "ENH: "
labels: [Enhancement, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to calista
        - label: >
            Changing existing functionality in calista
        - label: >
            Removing existing functionality in calista
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use calista to ..."
      placeholder: >
        I wish I could use calista to ...
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using pseudocode if relevant.
      placeholder: >
        Add a new function ...
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        Please describe any alternative solution (existing functionality, 3rd party package, etc.)
        that would satisfy the feature request.
      placeholder: >
           ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support
        the feature request.
